---

- hosts: all

  tasks:
    - name: Install Sensu GPG Key
      shell: wget -q https://sensu.global.ssl.fastly.net/apt/pubkey.gpg -O- | sudo apt-key add -

    - name: Install Sensu Repo
      shell: |
        . /etc/lsb-release
        sudo echo "deb     https://sensu.global.ssl.fastly.net/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/sensu.list

    - name: Install Sensu
      shell: |
        sudo apt-get update
        sudo apt-get install sensu nagios-plugins

    - template:
        src:
        dest: /etc/sensu/conf.d/client.json

    - copy:
        src: files/rabbitmq.json
        dest: /etc/sensu/conf.d/rabbitmq.json
        
