---

- hosts: all

  tasks:
    - name: Update Apt Cache
      apt:
        update_cache: yes

    - name: Install Sensu
      apt:
        pkg: sensu
        state: latest

    - name: Install Nagios Plugins
      apt:
        pkg: nagios-plugins
        state: latest
